services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - url-shortener-network
    volumes:
      - nginx_logs:/var/log/nginx

  app:
    build: .
    expose:
      - "3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/url_shortener
      - BASE_URL=http://localhost:8080
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - url-shortener-network

volumes:
  mongodb_data:
  nginx_logs:

networks:
  url-shortener-network:
    driver: bridge